### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by AIRobotZhang** [Sreyan88/ACLM#1]
Would you like to share the datasets across four low-resource settings (100, 200, 500, and 1000)?

**Comment by Sreyan88** [comment]
Hello @AIRobotZhang , Yes for sure! We will release code and datasets in 2 more days!

**Comment by AIRobotZhang** [comment]
> Hello @AIRobotZhang , Yes for sure! We will release code and datasets in 2 more days!

Hello @Sreyan88, is dataset coming? Thanks for your efforts.

**Comment by Utkarsh4430** [comment]
Hello @AIRobotZhang! Extremely sorry for the delay. I have pushed the code and the datasets to the repo. Please let me know if something needs to be added. I'll be adding some checkpoints in the coming days.

**Comment by Utkarsh4430** [comment]
Hello @AIRobotZhang! Extremely sorry for the delay. I have pushed the code and the datasets to the repo. Please let me know if something needs to be added. I'll be adding some checkpoints in the coming days.

**Comment by AIRobotZhang** [comment]
> Hello @AIRobotZhang! Extremely sorry for the delay. I have pushed the code and the datasets to the repo. Please let me know if something needs to be added. I'll be adding some checkpoints in the coming days.

Thanks for your wonderful work.
